### ISSUE TITLE
Error when using  calc_phylo_pseudotime with bcr data

### ISSUE THREAD

**Issue by semir2** [kunwang34/PhyloVelo#7]
Hi
Thank you for your great tool.
I have get an error when I use calc_phylo_pseudotime with bcr data, as flows:
 ` pv.calc_phylo_pseudotime(sd, r_sample=0.05, n_neighbors=100)
 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 631/656 [00:49<00:01, 12.78it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/blockstorage/anaconda3/envs/phylovelo2/lib/python3.9/site-packages/phylovelo/pseudo_time.py", line 142, in calc_phylo_pseudotime
    path = prim(graph, 0)
  File "/mnt/blockstorage/anaconda3/envs/phylovelo2/lib/python3.9/site-packages/phylovelo/pseudo_time.py", line 109, in prim
    nodes.remove(next)
KeyError: 630
`
The Version of python and other packages  is suite version which describled by github [requirements.txt](https://github.com/kunwang34/PhyloVelo/blob/master/requirements.txt) , what is more, when I add line with #  and got same error with same line(line 142 and  line 142).

Any suggestion for the tool? Or do you have developed environment with dockerfile?

Thanks

**Comment by semir2** [comment]
OK, Thanks.

Bests
